analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3497005,"name"\:"OrangeHRM Trial \#3497005","teamId"\:3491446,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3507587,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3491446,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
